service: ffly-poem-graphql

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:FFLY_AWS_REGION}
  stage: ${env:STAGE}
  profile: serverless
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables.
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${env:FFLY_AWS_REGION}:*:*"

custom:
  dotenv:
    path: /ffly-poem/ffconfig.env
    
functions:
  graphql:
    handler: graphql_handler.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get