service: ffly-poem-graphql

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: ${env:STAGE}
  profile: serverless
  environment: 
    STAGE: ${env:STAGE}
    GRAPHQL_PLAYGROUND_ENDPOINT: ${env:GRAPHQL_PLAYGROUND_ENDPOINT}

functions:
  graphql:
    handler: graphql_handler.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get