service: ffly-poem-graphql

plugins:
  - serverless-dotenv-plugin

package:
  include:
  - node_modules
  - build
  
provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:FFLY_AWS_REGION}
  stage: ${env:STAGE}
  profile: serverless
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${env:FFLY_AWS_REGION}:${env:FFLY_AWS_ACCOUNT_ID}:table/${env:AWS_DYNAMODB_META_TABLE}
    - Effect: Allow
      Action:
        - es:ESHttpPost
      ## Can't use exact resource name ${env:ELASTICSEARCH_DOMAIN_NAME} because aws is dumb.
      Resource: arn:aws:es:${env:FFLY_AWS_REGION}:${env:FFLY_AWS_ACCOUNT_ID}:domain/*

custom:
  # This will forward all env variables to lambda.
  dotenv:
    path: /ffly-poem/ffconfig.env

functions:
  graphql:
    handler: build/graphql_handler.handler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get