service: ffly-poem-graphql

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: dev #${env:STAGE}
  profile: serverless
  environment: 
    STAGE: ${env:STAGE}
#    NODE_ENV: ${env:NODE_ENV}  todo shawn, why this breaks graphql playground?

functions:
  graphql:
    handler: graphql_handler.handler
    events:
    - http:
        path: graphql
        method: post
    - http:
        path: graphql
        method: get