service: ffly-poem-client-web

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1 # serverless doesn't respect region in .aws/config
  profile: serverless

custom:
  s3Sync:
    - bucketName: ${self:service}
      localDir: build # Sync build folder.

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}
        WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: index.html