service: ffly-poem

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1 # serverless doesn't respect region in .aws/config
  profile: serverless

functions:
  graphql:
    handler: graphql_handler.handler
    events:
    - http:
        path: graphql
        method: post
    - http:
        path: graphql
        method: get